# Add one [[speakers]] block per Sonos speaker.
# The double brackets define a TOML array of tables.
[[speakers]]
ip = "192.168.1.X"
host = "name-sonos-1"
region = "us-east"

[[speakers]]
ip = "192.168.1.Y"
host = "name-sonos-2"
region = "us-east"

[influx2]
url = "https://192.168.1.X:8086"
org = "your-org"
token = "your-token"
verify_ssl = false
bucket = "your-bucket"
measurement = "net"
