[speaker]
ip = "192.168.1.X"
host = "name-sonos"
region = "us-east"

[influx2]
url = "https://192.168.1.X:8086"
org = "your-org"
token = "your-token"
verify_ssl = false
bucket = "your-bucket"
measurement = "net"
